/*
 * Class auto generated by TexturePacker
 *
 * Contains references to each image within the sprite sheet.
 *
 * https://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:d7ab211b7f83be78bf8c5acc5877827f:ad1d443fadc52f920b9733bd32c89dac:bb8c871ba50dcb594d48391b0a334787$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public class MainAtlas
	{
		public const string Applejack_afk1 = "applejack afk1";
		public const string Applejack_afk2 = "applejack afk2";
		public const string Applejack_afk3 = "applejack afk3";
		public const string Applejack_jump1 = "applejack-jump1";
		public const string Applejack_jump2 = "applejack-jump2";
		public const string Applejack_land1 = "applejack-land1";
		public const string Applejack_land2 = "applejack-land2";
		public const string Applejack_land3 = "applejack-land3";
		public const string Applejack_pony_idle1 = "applejack-pony-idle1";
		public const string Applejack_pony_idle2 = "applejack-pony-idle2";
		public const string Applejack_pony_star = "applejack-pony-star";
		public const string Applejack_pony_swim1 = "applejack-pony-swim1";
		public const string Applejack_pony_swim2 = "applejack-pony-swim2";
		public const string Applejack_pony_tap1 = "applejack-pony-tap1";
		public const string Applejack_pony_tap2 = "applejack-pony-tap2";
		public const string Applejack_true_idle = "applejack-true-idle";
		public const string Arbustes = "arbustes";
		public const string Coral1 = "coral1";
		public const string Coral2 = "coral2";
		public const string Coral3 = "coral3";
		public const string Coral4 = "coral4";
		public const string Coral5 = "coral5";
		public const string Coral6 = "coral6";
		public const string Coral7 = "coral7";
		public const string Cutie_cupcake_crew_applebloom1 = "cutie-cupcake-crew-applebloom1";
		public const string Cutie_cupcake_crew_applebloom2 = "cutie-cupcake-crew-applebloom2";
		public const string Cutie_cupcake_crew_applebloom3 = "cutie-cupcake-crew-applebloom3";
		public const string Cutie_cupcake_crew_applebloom4 = "cutie-cupcake-crew-applebloom4";
		public const string Cutie_cupcake_crew_cupcake_apple_bloom1 = "cutie-cupcake-crew-cupcake-apple-bloom1";
		public const string Cutie_cupcake_crew_cupcake_apple_bloom2 = "cutie-cupcake-crew-cupcake-apple-bloom2";
		public const string Cutie_cupcake_crew_cupcake_apple_bloom3 = "cutie-cupcake-crew-cupcake-apple-bloom3";
		public const string Cutie_cupcake_crew_cupcake_applebloom1 = "cutie-cupcake-crew-cupcake-applebloom1";
		public const string Cutie_cupcake_crew_cupcake_applebloom2 = "cutie-cupcake-crew-cupcake-applebloom2";
		public const string Cutie_cupcake_crew_cupcake_applebloom3 = "cutie-cupcake-crew-cupcake-applebloom3";
		public const string Cutie_cupcake_crew_cupcake_pinkie_pie1 = "cutie-cupcake-crew-cupcake-pinkie-pie1";
		public const string Cutie_cupcake_crew_cupcake_pinkie_pie2 = "cutie-cupcake-crew-cupcake-pinkie-pie2";
		public const string Cutie_cupcake_crew_cupcake_pinkie_pie3 = "cutie-cupcake-crew-cupcake-pinkie-pie3";
		public const string Cutie_cupcake_crew_cupcake_scootaloo1 = "cutie-cupcake-crew-cupcake-scootaloo1";
		public const string Cutie_cupcake_crew_cupcake_scootaloo2 = "cutie-cupcake-crew-cupcake-scootaloo2";
		public const string Cutie_cupcake_crew_cupcake_scootaloo3 = "cutie-cupcake-crew-cupcake-scootaloo3";
		public const string Cutie_cupcake_crew_cupcake_sweetie_belle1 = "cutie-cupcake-crew-cupcake-sweetie-belle1";
		public const string Cutie_cupcake_crew_cupcake_sweetie_belle2 = "cutie-cupcake-crew-cupcake-sweetie-belle2";
		public const string Cutie_cupcake_crew_cupcake_sweetie_belle3 = "cutie-cupcake-crew-cupcake-sweetie-belle3";
		public const string Cutie_cupcake_crew_pinkie_pie1 = "cutie-cupcake-crew-pinkie-pie1";
		public const string Cutie_cupcake_crew_pinkie_pie2 = "cutie-cupcake-crew-pinkie-pie2";
		public const string Cutie_cupcake_crew_pinkie_pie3 = "cutie-cupcake-crew-pinkie-pie3";
		public const string Cutie_cupcake_crew_scootaloo1 = "cutie-cupcake-crew-scootaloo1";
		public const string Cutie_cupcake_crew_scootaloo2 = "cutie-cupcake-crew-scootaloo2";
		public const string Cutie_cupcake_crew_scootaloo3 = "cutie-cupcake-crew-scootaloo3";
		public const string Cutie_cupcake_crew_sweetie_belle1 = "cutie-cupcake-crew-sweetie belle1";
		public const string Cutie_cupcake_crew_sweetie_belle2 = "cutie-cupcake-crew-sweetie belle2";
		public const string Cutie_cupcake_crew_sweetie_belle3 = "cutie-cupcake-crew-sweetie belle3";
		public const string Deco_m1 = "deco-m1";
		public const string Deco_m2 = "deco-m2";
		public const string Deco2 = "deco2";
		public const string Derpy = "derpy";
		public const string Derpy2 = "derpy2";
		public const string Enveloppe = "enveloppe";
		public const string Enveloppe1 = "enveloppe1";
		public const string Enveloppe2 = "enveloppe2";
		public const string Fences = "fences";
		public const string Fluttershy_pony_idle1 = "fluttershy-pony-idle1";
		public const string Fluttershy_pony_idle2 = "fluttershy-pony-idle2";
		public const string Fluttershy_pony_star = "fluttershy-pony-star";
		public const string Fluttershy_pony_swim1 = "fluttershy-pony-swim1";
		public const string Fluttershy_pony_swim2 = "fluttershy-pony-swim2";
		public const string Fluttershy_pony_tap1 = "fluttershy-pony-tap1";
		public const string Fluttershy_pony_tap2 = "fluttershy-pony-tap2";
		public const string Jump_effect = "jump effect";
		public const string Parcel1 = "parcel1";
		public const string Parcel2 = "parcel2";
		public const string Parcel3 = "parcel3";
		public const string Parcel4 = "parcel4";
		public const string Pinkiepie_pony_idle1 = "pinkiepie-pony-idle1";
		public const string Pinkiepie_pony_idle2 = "pinkiepie-pony-idle2";
		public const string Pinkiepie_pony_star = "pinkiepie-pony-star";
		public const string Pinkiepie_pony_swim1 = "pinkiepie-pony-swim1";
		public const string Pinkiepie_pony_swim2 = "pinkiepie-pony-swim2";
		public const string Pinkiepie_pony_tap1 = "pinkiepie-pony-tap1";
		public const string Pinkiepie_pony_tap2 = "pinkiepie-pony-tap2";
		public const string Planks_idle = "planks_idle";
		public const string Planks_left1 = "planks_left1";
		public const string Planks_left2 = "planks_left2";
		public const string Planks_left3 = "planks_left3";
		public const string Planks_left4 = "planks_left4";
		public const string Rainbow_trail = "rainbow_trail";
		public const string Rainbowdash_fail = "rainbowdash-fail";
		public const string Rainbowdash_idle1 = "rainbowdash-idle1";
		public const string Rainbowdash_idle2 = "rainbowdash-idle2";
		public const string Rainbowdash_idle3 = "rainbowdash-idle3";
		public const string Rainbowdash_jump1 = "rainbowdash-jump1";
		public const string Rainbowdash_jump2 = "rainbowdash-jump2";
		public const string Rainbowdash_land1 = "rainbowdash-land1";
		public const string Rainbowdash_land2 = "rainbowdash-land2";
		public const string Rainbowdash_land3 = "rainbowdash-land3";
		public const string Rarity_pony_idle1 = "rarity-pony-idle1";
		public const string Rarity_pony_idle2 = "rarity-pony-idle2";
		public const string Rarity_pony_star = "rarity-pony-star";
		public const string Rarity_pony_swim1 = "rarity-pony-swim1";
		public const string Rarity_pony_swim2 = "rarity-pony-swim2";
		public const string Rarity_pony_tap1 = "rarity-pony-tap1";
		public const string Rarity_pony_tap2 = "rarity-pony-tap2";
		public const string Sand1 = "sand1";
		public const string Sand2 = "sand2";
		public const string Sand3 = "sand3";
		public const string Seapony_parade_clap_effect = "seapony_parade_clap_effect";
		public const string Stand = "stand";
		public const string Table = "table";
		public const string Tree = "tree";
	}
}