/*
 * Class auto generated by TexturePacker
 *
 * Contains references to each image within the sprite sheet.
 *
 * https://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:06cb753c4aa47ae5caa9bd515cab1bfb:9b913dc060d4acf5ac2b1828f81fb05e:bb8c871ba50dcb594d48391b0a334787$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public class MainAtlas
	{
		public const string Applejack_afk1 = "applejack afk1";
		public const string Applejack_afk2 = "applejack afk2";
		public const string Applejack_afk3 = "applejack afk3";
		public const string Applejack_jump1 = "applejack-jump1";
		public const string Applejack_jump2 = "applejack-jump2";
		public const string Applejack_land1 = "applejack-land1";
		public const string Applejack_land2 = "applejack-land2";
		public const string Applejack_land3 = "applejack-land3";
		public const string Applejack_pony_idle1 = "applejack-pony-idle1";
		public const string Applejack_pony_idle2 = "applejack-pony-idle2";
		public const string Applejack_pony_star = "applejack-pony-star";
		public const string Applejack_pony_swim1 = "applejack-pony-swim1";
		public const string Applejack_pony_swim2 = "applejack-pony-swim2";
		public const string Applejack_pony_tap1 = "applejack-pony-tap1";
		public const string Applejack_pony_tap2 = "applejack-pony-tap2";
		public const string Applejack_true_idle = "applejack-true-idle";
		public const string Arbustes = "arbustes";
		public const string Coral1 = "coral1";
		public const string Coral2 = "coral2";
		public const string Coral3 = "coral3";
		public const string Coral4 = "coral4";
		public const string Coral5 = "coral5";
		public const string Coral6 = "coral6";
		public const string Coral7 = "coral7";
		public const string Fences = "fences";
		public const string Fluttershy_pony_idle1 = "fluttershy-pony-idle1";
		public const string Fluttershy_pony_idle2 = "fluttershy-pony-idle2";
		public const string Fluttershy_pony_star = "fluttershy-pony-star";
		public const string Fluttershy_pony_swim1 = "fluttershy-pony-swim1";
		public const string Fluttershy_pony_swim2 = "fluttershy-pony-swim2";
		public const string Fluttershy_pony_tap1 = "fluttershy-pony-tap1";
		public const string Fluttershy_pony_tap2 = "fluttershy-pony-tap2";
		public const string Jump_effect = "jump effect";
		public const string Pinkiepie_pony_idle1 = "pinkiepie-pony-idle1";
		public const string Pinkiepie_pony_idle2 = "pinkiepie-pony-idle2";
		public const string Pinkiepie_pony_star = "pinkiepie-pony-star";
		public const string Pinkiepie_pony_swim1 = "pinkiepie-pony-swim1";
		public const string Pinkiepie_pony_swim2 = "pinkiepie-pony-swim2";
		public const string Pinkiepie_pony_tap1 = "pinkiepie-pony-tap1";
		public const string Pinkiepie_pony_tap2 = "pinkiepie-pony-tap2";
		public const string Planks_idle = "planks_idle";
		public const string Planks_left1 = "planks_left1";
		public const string Planks_left2 = "planks_left2";
		public const string Planks_left3 = "planks_left3";
		public const string Planks_left4 = "planks_left4";
		public const string Rainbow_trail = "rainbow_trail";
		public const string Rainbowdash_fail = "rainbowdash-fail";
		public const string Rainbowdash_idle1 = "rainbowdash-idle1";
		public const string Rainbowdash_idle2 = "rainbowdash-idle2";
		public const string Rainbowdash_idle3 = "rainbowdash-idle3";
		public const string Rainbowdash_jump1 = "rainbowdash-jump1";
		public const string Rainbowdash_jump2 = "rainbowdash-jump2";
		public const string Rainbowdash_land1 = "rainbowdash-land1";
		public const string Rainbowdash_land2 = "rainbowdash-land2";
		public const string Rainbowdash_land3 = "rainbowdash-land3";
		public const string Rarity_pony_idle1 = "rarity-pony-idle1";
		public const string Rarity_pony_idle2 = "rarity-pony-idle2";
		public const string Rarity_pony_star = "rarity-pony-star";
		public const string Rarity_pony_swim1 = "rarity-pony-swim1";
		public const string Rarity_pony_swim2 = "rarity-pony-swim2";
		public const string Rarity_pony_tap1 = "rarity-pony-tap1";
		public const string Rarity_pony_tap2 = "rarity-pony-tap2";
		public const string Sand1 = "sand1";
		public const string Sand2 = "sand2";
		public const string Sand3 = "sand3";
		public const string Seapony_parade_clap_effect = "seapony_parade_clap_effect";
		public const string Stand = "stand";
		public const string Tree = "tree";
	}
}