/*
 * Class auto generated by TexturePacker
 *
 * Contains references to each image within the sprite sheet.
 *
 * https://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:5a0857bbf0ef6126944dd4430bd41a18:60bc0a1fbbce23d5bf08f4f47c070ea1:bb8c871ba50dcb594d48391b0a334787$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public class MainAtlas
	{
		public const string Applejack_afk1 = "applejack afk1";
		public const string Applejack_afk2 = "applejack afk2";
		public const string Applejack_afk3 = "applejack afk3";
		public const string Applejack_jump1 = "applejack-jump1";
		public const string Applejack_jump2 = "applejack-jump2";
		public const string Applejack_land1 = "applejack-land1";
		public const string Applejack_land2 = "applejack-land2";
		public const string Applejack_land3 = "applejack-land3";
		public const string Applejack_pony_idle1 = "applejack-pony-idle1";
		public const string Applejack_pony_idle2 = "applejack-pony-idle2";
		public const string Applejack_pony_star = "applejack-pony-star";
		public const string Applejack_pony_swim1 = "applejack-pony-swim1";
		public const string Applejack_pony_swim2 = "applejack-pony-swim2";
		public const string Applejack_pony_tap1 = "applejack-pony-tap1";
		public const string Applejack_pony_tap2 = "applejack-pony-tap2";
		public const string Applejack_true_idle = "applejack-true-idle";
		public const string Coral1 = "coral1";
		public const string Coral2 = "coral2";
		public const string Coral3 = "coral3";
		public const string Coral4 = "coral4";
		public const string Coral5 = "coral5";
		public const string Coral6 = "coral6";
		public const string Coral7 = "coral7";
		public const string Pinkiepie_pony_idle1 = "pinkiepie-pony-idle1";
		public const string Pinkiepie_pony_idle2 = "pinkiepie-pony-idle2";
		public const string Pinkiepie_pony_star = "pinkiepie-pony-star";
		public const string Pinkiepie_pony_swim1 = "pinkiepie-pony-swim1";
		public const string Pinkiepie_pony_swim2 = "pinkiepie-pony-swim2";
		public const string Pinkiepie_pony_tap1 = "pinkiepie-pony-tap1";
		public const string Pinkiepie_pony_tap2 = "pinkiepie-pony-tap2";
		public const string Rainbowdash_fail = "rainbowdash-fail";
		public const string Rainbowdash_idle1 = "rainbowdash-idle1";
		public const string Rainbowdash_idle2 = "rainbowdash-idle2";
		public const string Rainbowdash_idle3 = "rainbowdash-idle3";
		public const string Rainbowdash_jump1 = "rainbowdash-jump1";
		public const string Rainbowdash_jump2 = "rainbowdash-jump2";
		public const string Rainbowdash_land1 = "rainbowdash-land1";
		public const string Rainbowdash_land2 = "rainbowdash-land2";
		public const string Rainbowdash_land3 = "rainbowdash-land3";
		public const string Sand1 = "sand1";
		public const string Sand2 = "sand2";
		public const string Sand3 = "sand3";
		public const string Sprite_0001 = "Sprite-0001";
		public const string Sprite_0002 = "Sprite-0002";
		public const string Template_pony_idle1 = "template-pony-idle1";
		public const string Template_pony_idle2 = "template-pony-idle2";
		public const string Template_pony_star = "template-pony-star";
		public const string Template_pony_swim1 = "template-pony-swim1";
		public const string Template_pony_swim2 = "template-pony-swim2";
		public const string Template_pony_tap1 = "template-pony-tap1";
		public const string Template_pony_tap2 = "template-pony-tap2";
		
	}
}